name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    env:
      QASE_MODE: "testops"
      QASE_TESTOPS_PROJECT: "DEMO"
      QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI and Newman
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          npm install -g newman
          npm install -g newman-reporter-qase
      - name: Run API tests and send results to Qase
        run: |
          newman run ./example_1.postman_collection.json -r qase \
            --reporter-qase-runName="GitHub Actions API Tests"
